apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::568107119472:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1GIR1LF5CY5BC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::568107119472:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-14T13:39:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1530"
  uid: e3a804da-9d84-482f-9acf-98c24ebb99e9
