AWSTemplateFormatVersion: 2010-09-09
Description: Udacity - This template deploys a VPC and APC
Resources:
  myUdacityVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: 'true'